spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/iotDevices
    username: root
    password: 123
  sql:
    init:
      platform: postgres
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create